import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import './globals.css'
import StyledComponentsRegistry from '@/lib/AntdRegistry'
import { GoogleOAuthProvider } from '@react-oauth/google'
import { MainContext } from '@/context/MainContext'

const inter = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Tennis Booking',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <GoogleOAuthProvider clientId="7627494060-ett5o73n48suh7s1eucel93nju2r1o8d.apps.googleusercontent.com">
          <StyledComponentsRegistry>
            <MainContext>
              {children}
            </MainContext>
          </StyledComponentsRegistry>
        </GoogleOAuthProvider>
      </body>
    </html>
  )
}
